testing simplified signing step

diff --git a/.github/workflows/build_debian_source_package.yml b/.github/workflows/build_debian_source_package.yml
--- a/.github/workflows/build_debian_source_package.yml
+++ b/.github/workflows/build_debian_source_package.yml
@@ -474,47 +474,33 @@ jobs:
         # Change directory to package-source
         cd package-source
 
-        # Manually sign the .dsc file using gpg
+        # Sign the .dsc file using debsign
         DSC_FILE=$(ls *.dsc | head -n 1)
         if [ -f "$DSC_FILE" ]; then
           echo "Signing .dsc file: $DSC_FILE"
-          echo "File path: $(realpath "$DSC_FILE")"
-          echo "File contents:"
-          cat "$DSC_FILE"
-          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --default-key ${GPG_KEY_FINGERPRINT} --output "${DSC_FILE}.asc" --detach-sign "$DSC_FILE"
+          debsign -k${GPG_KEY_FINGERPRINT} "$DSC_FILE"
           if [ $? -ne 0 ]; then
-            echo "Error: Failed to detach-sign the .dsc file."
+            echo "Error: Failed to sign the .dsc file."
             exit 1
           fi
-          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --default-key ${GPG_KEY_FINGERPRINT} --clearsign --output "${DSC_FILE}.signed" "${DSC_FILE}.asc"
-          if [ $? -ne 0 ]; then
-            echo "Error: Failed to clearsign the .asc file."
-            exit 1
-          fi
-          mv "${DSC_FILE}.signed" "$DSC_FILE"
-          rm "${DSC_FILE}.asc"
         else
           echo "Error: No .dsc file found."
           exit 1
         fi
 
-        # Sign the .changes file using dpkg-sig
+        # Sign the .changes file using debsign
         CHANGES_FILE=$(ls *_source.changes | head -n 1)
-
-        # Recalculate checksums
-        debsign -k${GPG_KEY_FINGERPRINT} "$CHANGES_FILE"
-
         if [ -f "$CHANGES_FILE" ]; then
           echo "Signing .changes file: $CHANGES_FILE"
-          dpkg-sig --sign builder -k ${GPG_KEY_FINGERPRINT} "$CHANGES_FILE"
+          debsign -k${GPG_KEY_FINGERPRINT} "$CHANGES_FILE"
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to sign the .changes file."
+            exit 1
+          fi
         else
           echo "Error: No .changes file found."
           exit 1
         fi
-
-      env:
-        GPG_EMAIL: ${{ secrets.GPG_EMAIL }}
-        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
 
     - name: '[general] - Upload to PPA'
       run: |
