debug

diff --git a/.github/workflows/build_debian_source_package.yml b/.github/workflows/build_debian_source_package.yml
--- a/.github/workflows/build_debian_source_package.yml
+++ b/.github/workflows/build_debian_source_package.yml
@@ -400,7 +400,7 @@ jobs:
         export GPG_TTY=$(tty)
 
         # Extract the GPG Key Fingerprint
-        GPG_KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons --fingerprint | awk -F: '/^fpr/{print $10}')
+        GPG_KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons --fingerprint | awk -F: '/^fpr/{print $10; exit}')
         echo "GPG Key Fingerprint: $GPG_KEY_FINGERPRINT"
 
         echo "Listing files in package-source directory:"
@@ -414,14 +414,13 @@ jobs:
         ls -l *_source.changes
 
         # Sign the source changes file using the key fingerprint
-        for changes_file in *_source.changes; do
-          if [ -f "$changes_file" ]; then
-            debsign -k${GPG_KEY_FINGERPRINT} "$changes_file"
-          else
-            echo "Error: No source changes file found."
-            exit 1
-          fi
-        done
+        changes_file=$(ls *_source.changes | head -n 1)
+        if [ -f "$changes_file" ]; then
+          debsign -k${GPG_KEY_FINGERPRINT} "$changes_file"
+        else
+          echo "Error: No source changes file found."
+          exit 1
+        fi
       env:
         GPG_EMAIL: ${{ secrets.GPG_EMAIL }}
 
