debug

diff --git a/.github/workflows/build_debian_source_package.yml b/.github/workflows/build_debian_source_package.yml
--- a/.github/workflows/build_debian_source_package.yml
+++ b/.github/workflows/build_debian_source_package.yml
@@ -401,9 +401,25 @@ jobs:
 
         # Extract the GPG Key Fingerprint
         GPG_KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons --fingerprint | awk -F: '/^fpr/{print $10}')
+        echo "GPG Key Fingerprint: $GPG_KEY_FINGERPRINT"
+
+        echo "Listing files in package-source directory:"
+        ls -l package-source
+
+        # List the specific source changes file
+        echo "Listing *_source.changes files:"
+        ls -l package-source/*_source.changes
+
         # Sign the source changes file using the key fingerprint
         cd package-source
-        debsign -k${GPG_KEY_FINGERPRINT} *_source.changes
+        for changes_file in *_source.changes; do
+          if [ -f "$changes_file" ]; then
+            debsign -k${GPG_KEY_FINGERPRINT} "$changes_file"
+          else
+            echo "Error: No source changes file found."
+            exit 1
+          fi
+        done
       env:
         GPG_EMAIL: ${{ secrets.GPG_EMAIL }}
 
